credentials:
  usernames:
    liuysh:
      email: liuysh20@gmail.com
      name: Luis Leonard
      password: # Placeholder for hashed password of 'abc'
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: # Placeholder for hashed password of 'def'
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com